// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const mongodbUrl = process.env["MONGODB_URL"];
if (!mongodbUrl) {
  throw new Error("Missing required environment variable: MONGODB_URL");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: mongodbUrl,
  },
});
